# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "sq-spec-portal-tfstate"
    encrypt      = true
    key          = "dev/containerize/erc/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
